import type { NextPage, GetServerSidePropsContext } from "next";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { City, CityWithWeatherForecast } from "../types";
import { Row, Header } from "../components";

interface HomeProps {
  citiesWithWeatherForecast: CityWithWeatherForecast[];
}

const Home: NextPage<HomeProps> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Været i Norges fem mest befolkede byer!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <table>
          <Header />
          <tbody>
            {props.citiesWithWeatherForecast.map((city) => (
              <Row key={city.city} city={city} />
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default Home;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const topFiveMostPopulousCities: City[] = require("./cities.json").slice(
    0,
    5
  );

  const citiesWithWeatherForecast: CityWithWeatherForecast[] =
    await Promise.all(
      topFiveMostPopulousCities.map(async (city) => {
        const weatherForecast = await axios.get(
          `https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=${city.lat}&lon=${city.lng}`
        );
        return { ...city, weatherForecast: weatherForecast.data };
      })
    );

  return {
    props: {
      citiesWithWeatherForecast,
    },
  };
}
